//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participation
    {
        public int ParticipationId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<int> RaceNumber { get; set; }
        public string FinalPosition { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Race Race { get; set; }
    }
}
